INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('001','Student01','Marcopolo','Ramos','Peña',GetDate(),'RAPM770129234234','mpolox@gmail.com','321654987','','Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('002','Student01','Pancho','Ramos','Peña',GetDate(),'Pancho-129234234','Pancho@gmail.com','321654987','','Pancho Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('003','Student01','Jose','Ramos','Peña',GetDate(),'Jose-129234234','Jose@gmail.com','321654987','','Jose Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('004','Student01','Alejandro','Ramos','Peña',GetDate(),'Alejandro-129234234','Alejandro@gmail.com','321654987','','Alejandro Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('005','Student01','Rosa','Ramos','Peña',GetDate(),'Rosa-129234234','Rosa@gmail.com','321654987','','Rosa Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('006','Student01','Maria','Ramos','Peña',GetDate(),'Maria-129234234','Maria@gmail.com','321654987','','Maria Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('007','Student01','Monica','Ramos','Peña',GetDate(),'Monica-129234234','Monica@gmail.com','321654987','','Monica Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('008','Student01','Marcelo','Ramos','Peña',GetDate(),'Marcelo-129234234','Marcelo@gmail.com','321654987','','Marcelo Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('009','Student01','Bryan','Ramos','Peña',GetDate(),'Bryan-129234234','Bryan@gmail.com','321654987','','Bryan Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('010','Student01','Emilia','Ramos','Peña',GetDate(),'Emilia-129234234','Emilia@gmail.com','321654987','','Emilia Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('011','Student01','Polo','Ramos','Peña',GetDate(),'Polo-129234234','Polo@gmail.com','321654987','','Polo Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('012','Student01','Jaime','Ramos','Peña',GetDate(),'Jaime-129234234','Jaime@gmail.com','321654987','','Jaime Aqui en la casa ')
INSERT INTO Students (StudentId, StudentName, FirstName, ParentName, MotherName, Birthday, Curp, Email, CellPhone,Phone, Address) 
VALUES ('013','Student01','Victor','Ramos','Peña',GetDate(),'Victor-129234234','Victor@gmail.com','321654987','','Victor Aqui en la casa ')

INSERT INTO Rooms (Name,Number) VALUES ('Salon 1','1')
INSERT INTO Rooms (Name,Number) VALUES ('Salon 2','2')
INSERT INTO Rooms (Name,Number) VALUES ('Salon 3','3')
INSERT INTO Rooms (Name,Number) VALUES ('Salon 4','4')
INSERT INTO Rooms (Name,Number) VALUES ('Salon 5','5')
INSERT INTO Rooms (Name,Number) VALUES ('Salon 6','6')
INSERT INTO Rooms (Name,Number) VALUES ('Salon 7','7')
INSERT INTO Rooms (Name,Number) VALUES ('Salon 8','8')
INSERT INTO Rooms (Name,Number) VALUES ('Salon 9','9')
INSERT INTO Rooms (Name,Number) VALUES ('Salon 10','10')


INSERT INTO Teachers (Code,Description,FirstName,ParentName,MotherName,Birthday,Curp,Email,CellPhone,Phone,Address)
VALUES ('Code01','Teacher Description 01','Teacher01','ParentName01','MotherName01',GetDate(),'TeacherCURP01','Teacher@gmail.com01','1000000001','200000001','TeaherAddress01')
INSERT INTO Teachers (Code,Description,FirstName,ParentName,MotherName,Birthday,Curp,Email,CellPhone,Phone,Address)
VALUES ('Code02','Teacher Description 02','Teacher02','ParentName02','MotherName02',GetDate(),'TeacherCURP02','Teacher@gmail.com02','1000000001','200000001','TeaherAddress02')
INSERT INTO Teachers (Code,Description,FirstName,ParentName,MotherName,Birthday,Curp,Email,CellPhone,Phone,Address)
VALUES ('Code03','Teacher Description 03','Teacher03','ParentName03','MotherName03',GetDate(),'TeacherCURP03','Teacher@gmail.com03','1000000001','200000001','TeaherAddress03')
INSERT INTO Teachers (Code,Description,FirstName,ParentName,MotherName,Birthday,Curp,Email,CellPhone,Phone,Address)
VALUES ('Code04','Teacher Description 04','Teacher04','ParentName04','MotherName04',GetDate(),'TeacherCURP04','Teacher@gmail.com04','1000000001','200000001','TeaherAddress04')
INSERT INTO Teachers (Code,Description,FirstName,ParentName,MotherName,Birthday,Curp,Email,CellPhone,Phone,Address)
VALUES ('Code05','Teacher Description 05','Teacher05','ParentName05','MotherName05',GetDate(),'TeacherCURP05','Teacher@gmail.com05','1000000001','200000001','TeaherAddress05')
INSERT INTO Teachers (Code,Description,FirstName,ParentName,MotherName,Birthday,Curp,Email,CellPhone,Phone,Address)
VALUES ('Code06','Teacher Description 06','Teacher06','ParentName06','MotherName06',GetDate(),'TeacherCURP06','Teacher@gmail.com06','1000000001','200000001','TeaherAddress06')
INSERT INTO Teachers (Code,Description,FirstName,ParentName,MotherName,Birthday,Curp,Email,CellPhone,Phone,Address)
VALUES ('Code07','Teacher Description 07','Teacher07','ParentName07','MotherName07',GetDate(),'TeacherCURP07','Teacher@gmail.com07','1000000001','200000001','TeaherAddress07')
INSERT INTO Teachers (Code,Description,FirstName,ParentName,MotherName,Birthday,Curp,Email,CellPhone,Phone,Address)
VALUES ('Code08','Teacher Description 08','Teacher08','ParentName08','MotherName08',GetDate(),'TeacherCURP08','Teacher@gmail.com08','1000000001','200000001','TeaherAddress08')
INSERT INTO Teachers (Code,Description,FirstName,ParentName,MotherName,Birthday,Curp,Email,CellPhone,Phone,Address)
VALUES ('Code09','Teacher Description 09','Teacher09','ParentName09','MotherName09',GetDate(),'TeacherCURP09','Teacher@gmail.com09','1000000001','200000001','TeaherAddress09')
INSERT INTO Teachers (Code,Description,FirstName,ParentName,MotherName,Birthday,Curp,Email,CellPhone,Phone,Address)
VALUES ('Code10','Teacher Description 10','Teacher10','ParentName10','MotherName10',GetDate(),'TeacherCURP10','Teacher@gmail.com10','1000000001','200000001','TeaherAddress10')

INSERT INTO Subjects (Name,Description,Credits,ShortName)
VALUES ('TLR 1','TLR 1','10','TLR 1')
INSERT INTO Subjects (Name,Description,Credits,ShortName)
VALUES ('TLR 2','TLR 2','10','TLR 2')
INSERT INTO Subjects (Name,Description,Credits,ShortName)
VALUES ('MATE 1','MATE 1','10','MATE 1')
INSERT INTO Subjects (Name,Description,Credits,ShortName)
VALUES ('MATE 2','MATE 2','10','MATE 2')
INSERT INTO Subjects (Name,Description,Credits,ShortName)
VALUES ('MATE 3','MATE 3','10','MATE 3')
INSERT INTO Subjects (Name,Description,Credits,ShortName)
VALUES ('ARTE 1','ARTE 1','5','ARTE 1')
INSERT INTO Subjects (Name,Description,Credits,ShortName)
VALUES ('ARTE 2','ARTE 2','5','ARTE 2')
INSERT INTO Subjects (Name,Description,Credits,ShortName)
VALUES ('FISICA 1','FISICA 1','10','FISICA 1')
INSERT INTO Subjects (Name,Description,Credits,ShortName)
VALUES ('FISICA 2','FISICA 2','10','FISICA 2')

INSERT INTO clases (Description,RoomId,SubjectId)
VALUES ('Descripcion de la clase 1',1,1)
INSERT INTO clases (Description,RoomId,SubjectId)
VALUES ('Descripcion de la clase 2',2,2)
INSERT INTO clases (Description,RoomId,SubjectId)
VALUES ('Descripcion de la clase 3',3,3)
INSERT INTO clases (Description,RoomId,SubjectId)
VALUES ('Descripcion de la clase 4',4,4)
INSERT INTO clases (Description,RoomId,SubjectId)
VALUES ('Descripcion de la clase 5',5,5)
INSERT INTO clases (Description,RoomId,SubjectId)
VALUES ('Descripcion de la clase 6',6,6)
INSERT INTO clases (Description,RoomId,SubjectId)
VALUES ('Descripcion de la clase 7',7,7)
INSERT INTO clases (Description,RoomId,SubjectId)
VALUES ('Descripcion de la clase 8',8,8)
INSERT INTO clases (Description,RoomId,SubjectId)
VALUES ('Descripcion de la clase 9',9,9)
INSERT INTO clases (Description,RoomId,SubjectId)
VALUES ('Descripcion de la clase 10',10,10)



INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 1',1,11)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 2',3,11)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 3',4,11)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 4',6,12)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 5',7,11)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 6',9,12)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 7',1,12)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 8',2,12)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 9',7,12)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 10',9,13)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 11',1,13)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 12',1,13)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 13',4,14)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 14',5,14)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 15',8,14)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 16',9,14)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 17',8,7)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 18',6,7)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 19',5,7)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 20',3,7)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 21',1,8)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 22',2,8)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 23',3,8)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 24',5,8)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 25',7,9)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 26',9,9)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 27',1,9)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 28',3,10)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 29',5,10)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 30',6,10)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 31',8,10)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 32',3,9)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 33',4,7)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 34',5,5)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 35',6,3)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 36',7,2)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 37',3,1)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 38',7,3)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 39',9,4)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 40',8,6)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 41',6,8)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 42',5,10)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 43',4,2)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 44',3,3)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 45',1,5)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 46',2,7)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 47',3,9)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 48',5,4)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 49',7,1)
INSERT INTO ClaseStudents(Descripcion,ClaseId,StudentId)
VALUES ('Descripcion de la relacion 50',1,	2)


SaltilloMexico86!